fixed incorrect variable returned
Copy/Pasted code caused the below error, variable returned updated.
```
Script Default snippet error: Traceback (most recent call last):
  File "<string>", line 433, in <module>
  File "<string>", line 425, in main
  File "<string>", line 391, in pointer_renamer
NameError: global name 'strings_added' is not defined
```